// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'e_learning';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String COUNTRYCODE = 'assets/countrycode.json';
  static const String APPLE = 'assets/images/apple.svg';
  static const String E_LOGO = 'assets/images/e_logo.png';
  static const String FACEBOOK = 'assets/images/facebook.svg';
  static const String GOOGLE = 'assets/images/google.svg';
  static const String LOGO_BLUE = 'assets/images/logo_blue.png';
  static const String ONBOARDING_1 = 'assets/images/onboarding_1.png';
  static const String ONBOARDING_2 = 'assets/images/onboarding_2.png';
  static const String ONBOARDING_3 = 'assets/images/onboarding_3.png';
}
